src/Entity/BlogPost.php
<?php

namespace App\Entity;

use App\Repository\BlogPostRepository;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: BlogPostRepository::class)]
class BlogPost
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column(type: 'integer')]
    private $id;

    #[ORM\Column(type: 'string', length: 255)]
    private $title;

    #[ORM\Column(type: 'text', nullable: true)]
    private $description;

    #[ORM\Column(type: 'datetime')]
    private $created_at;

    #[ORM\Column(type: 'string', length: 255, nullable: true)]
    private $additional_links;

    #[ORM\ManyToOne(targetEntity: BlogCategory::class, inversedBy: 'post')]
    #[ORM\JoinColumn(nullable: false)]
    private $category;

    #[ORM\Column(type: 'text')]
    private $content;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): self
    {
        $this->title = $title;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(?string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getCreatedAt(): ?\DateTime
    {
        return $this->created_at;
    }

    public function setCreatedAt(\DateTime $created_at): self
    {
        $this->created_at = $created_at;

        return $this;
    }

    public function getAdditionalLinks(): ?string
    {
        return $this->additional_links;
    }

    public function setAdditionalLinks(?string $additional_links): self
    {
        $this->additional_links = $additional_links;

        return $this;
    }

    public function getCategory(): ?BlogCategory
    {
        return $this->category;
    }

    public function setCategory(?BlogCategory $category): self
    {
        $this->category = $category;

        return $this;
    }

    public function getContent(): ?string
    {
        return $this->content;
    }

    public function setContent(string $content): self
    {
        $this->content = $content;

        return $this;
    }
//    public function __toString()
//    {
//        return $this->created_at;
//    }
}

src/Controller/BlogController.php
<?php
namespace App\Controller;
use App\Form\BlogPostFormType;
use Symfony\Component\Form\FormTypeInterface;
use App\Entity\BlogCategory;
use App\Entity\BlogPost;
use App\Repository\BlogCategoryRepository;
use Doctrine\Persistence\ManagerRegistry;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\HttpFoundation\Request;
use App\Form\CategoryformType;

class BlogController extends  AbstractController
{

    public function view(ManagerRegistry $doctrine,int $id): Response
    {
        if($id != 0 ) {
            $category = $doctrine->getRepository(BlogCategory::class)->find($id);
            $posts = $category->getPost();
        }
        else{
            $posts = $doctrine->getRepository(BlogPost::class)->findAll();
        }
        return $this->render('blog/view.html.twig',[
            "posts"=>$posts,
        ]);
    }
    public function showpost(ManagerRegistry $doctrine,int $id): Response
    {
        $post= $doctrine->getRepository(BlogPost::class)->find($id);
        return $this->render('blog/showpost.html.twig',[
            "post"=>$post,
        ]);
    }
    public function index(): Response
    {
        $name = "Homepage";
        return $this->render('blog/index.html.twig',[
            "name"=>$name,
        ]);
    }

    public function list(ManagerRegistry $doctrine): Response
    {
        $repository = $doctrine->getRepository(BlogCategory::class);
        $blogCategories = $repository->findAll();

        return $this->render('blog/list.html.twig',[
            "blogCategories"=>$blogCategories,
        ]);
    }
    public function newcat(Request $request,ManagerRegistry $doctrine)
    {
        $category = new BlogCategory();

        $form = $this->createForm(CategoryformType::class, $category);
        $form->handleRequest($request);

        if($form->isSubmitted()&&$form->isValid())
        {
            $em = $doctrine->getManager();
            $em->persist($category);
            $em->flush();
        }

        return $this->render('blog/newcat.html.twig',[
            'form'=>$form->createView(),
        ]);
    }
    public function newpost(Request $request,ManagerRegistry $doctrine): Response
    {
    $post = new BlogPost();

        $form = $this->createForm(BlogPostFormType::class, $post);
        $form->handleRequest($request);
        if($form->isSubmitted()&&$form->isValid())
        {
            $em = $doctrine->getManager();
            $em->persist($post);
            $em->flush();
        }
    return $this->render('blog/newpost.html.twig',[
        'form'=>$form->createView(),
    ]);
}

    public function login(): Response
    {
        $name = "Login";
        return $this->render('blog/login.html.twig',[
            "name"=>$name,
        ]);
    }
    public function contact(): Response
    {
        $name = "Contact";
        return $this->render('blog/contact.html.twig',[
            "name"=>$name,
        ]);
    }

}

templates/blog/contact.html.twig
{% extends "blog/index.html.twig" %}
{% block content%}
    {{ parent() }}
    <p>contact me</p>
{% endblock %}

templates/blog/index.html.twig
<html>
<head>
    {% block tittle %}
    <title>Blog Title</title>
    {% endblock %}
</head>
<body>
{% block body %}
<div>
    {% block links %}
    <a href="{{ url('index')}}" title="Home">Homepage</a>
    <a href="{{ url('list')}}" title="List">Article List</a>
    <a href="{{ url('login')}}" title="Login">Login</a>
    <a href="{{ url('contact')}}" title="Contact">Contact</a>
    {% endblock %}
</div>
{% block content %}

{% endblock %}
{% endblock %}
</body>
</html>

templates/blog/list.html.twig
{% extends "blog/index.html.twig" %}
{% block content%}
    <ul>
        {% for category in blogCategories %}
        <li><a href="{{ url('view',{'id':category.id}) }}">{{ category.name }}</li>
        {% endfor %}
    </ul>
    <p><a href="{{ url('view',{'id':0}) }}">Show all posts</p>
    <p><a href="{{ url('newcat') }}">New category<a href="{{ url('newpost') }}">New post</p>
{% endblock %}

templates/blog/login.html.twig
{% extends "blog/index.html.twig" %}
{% block content%}
    {{ parent() }}
    <div>
        <h4>LOGIN:</h4>
        <h4>PASSWORD:</h4>
    </div>
{% endblock %}

templates/blog/newcat.html.twig
{% extends "blog/index.html.twig" %}
{% block content%}
    {{ parent() }}
    {{ form(form) }}
{% endblock %}

templates/blog/newpost.html.twig
{% extends "blog/index.html.twig" %}
{% block content%}
    {{ parent() }}
    {{ form(form) }}
{% endblock %}

templates/blog/showpost.html.twig
{% extends "blog/index.html.twig" %}
{% block content%}
    <h1>{{ post.title }}</h1>
    <h5>{{ post.createdAt|date("m/d/Y") }}</h5>
    <p>{{ post.description }}</p>
    <p>{{ post.content }}</p>
    <h3>{{ post.additionalLinks }}</h3>
{% endblock %}

templates/blog/view.html.twig
{% extends "blog/list.html.twig" %}
{% block content%}
    <table>
        <tr>
            <td>Title</td>
            <td>Description</td>
        </tr>
    {% for post in posts %}

        <tr>
            <td><a href="{{ url('showpost',{'id':post.id}) }}">{{ post.title }}  </td>
            <td>{{ post.description }}</td>
        </tr>
    {% endfor %}
    </table>
{% endblock %}